// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Final.Models;

namespace ProyectoFinal.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20181112201006_proyecto-final_reservas_apellido")]
    partial class proyectofinal_reservas_apellido
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Proyecto_Final.Models.Entidades.Contacto", b =>
                {
                    b.Property<int>("idContacto")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Asunto")
                        .IsRequired();

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("Mensaje")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("idContacto");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Entidades.Reserva", b =>
                {
                    b.Property<int>("codReserva")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<DateTime>("Fecha");

                    b.Property<DateTime>("Hora");

                    b.Property<string>("Nombre");

                    b.Property<int?>("UsuarioidUsuario");

                    b.Property<int>("numPersonas");

                    b.HasKey("codReserva");

                    b.HasIndex("UsuarioidUsuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Entidades.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("Nombre");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("Telefono");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuario");

                    b.HasData(
                        new { idUsuario = 1, Apellido = "Choque Chara", Correo = "sol.choque@usil.pe", Nombre = "Sol Milagros", Password = "12345", Telefono = 1256456778 },
                        new { idUsuario = 2, Apellido = "Alayo Cuje", Correo = "yaneli.alayo@usil.pe", Nombre = "Yaneli ", Password = "678910", Telefono = 456845543 }
                    );
                });

            modelBuilder.Entity("Proyecto_Final.Models.Entidades.Reserva", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Entidades.Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioidUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
