// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Final.Models;

namespace ProyectoFinal.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20181105224947_CreacionDB")]
    partial class CreacionDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Proyecto_Final.Models.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Nombre");

                    b.Property<int>("Telefono");

                    b.HasKey("idCliente");

                    b.ToTable("Cliente");

                    b.HasData(
                        new { idCliente = 1, Apellido = "Choque Chara", Nombre = "Sol Milagros", Telefono = 1256456778 },
                        new { idCliente = 2, Apellido = "Alayo Cuje", Nombre = "Yaneli ", Telefono = 456845543 }
                    );
                });

            modelBuilder.Entity("Proyecto_Final.Models.Menu", b =>
                {
                    b.Property<int>("idMenu")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.Property<float>("Precio");

                    b.HasKey("idMenu");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Reserva", b =>
                {
                    b.Property<int>("codReserva")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Fecha");

                    b.Property<DateTime>("Hora");

                    b.Property<int?>("MenuidMenu");

                    b.Property<float>("Monto");

                    b.Property<int?>("idCliente");

                    b.HasKey("codReserva");

                    b.HasIndex("MenuidMenu");

                    b.HasIndex("idCliente");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Reserva", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Menu")
                        .WithMany("Reserva")
                        .HasForeignKey("MenuidMenu");

                    b.HasOne("Proyecto_Final.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("idCliente");
                });
#pragma warning restore 612, 618
        }
    }
}
